services:
  - type: web
    name: hospital-api
    env: docker
    repo: https://github.com/oyeludeelijah/Hospital-App-.git
    region: oregon
    plan: free
    branch: main
    buildCommand: cd HospitalApp.web/HospitalApi && docker build -t hospital-api .
    startCommand: cd HospitalApp.web/HospitalApi && docker run -p 8080:80 hospital-api
    healthCheckPath: /api/hello
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=hospital.db
    autoDeploy: true 