version: '3.8'

services:
  api:
    build:
      context: ./HospitalApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hospital_dev
      - JWT_KEY=your-development-jwt-key-min-32-chars
    depends_on:
      - db
    volumes:
      - ./HospitalApi:/src
      - /src/bin
      - /src/obj

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hospital_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 